import type { Model } from "./types";

/** Checked against each source on 2026-09-22. */
export const models: Model[] = [
  {
    id: "claude-fable-5-1",
    name: "Claude Fable 5.1",
    provider: "Anthropic",
    apiId: "claude-fable-5-1",
    class: "frontier",
    released: "2026-09-01",
    contextWindow: 1_000_000,
    maxOutput: 128_000,
    price: { input: 10, output: 50, cachedInput: 0.25 },
    openWeight: false,
    license: null,
    note: "Anthropic’s most capable generally available model. Batch API is 50% off.",
    sources: [{ label: "model page", url: "https://platform.claude.com/docs/en/models/fable-5-1/overview" }, { label: "announcement", url: "https://www.anthropic.com/claude-fable-and-mythos-5-1" }],
  },
  {
    id: "claude-opus-5-5",
    name: "Claude Opus 5.5",
    provider: "Anthropic",
    apiId: "claude-opus-5-5",
    class: "frontier",
    released: "2026-09-22",
    contextWindow: 1_000_000,
    maxOutput: 128_000,
    price: { input: 4, output: 20, cachedInput: 0.2 },
    openWeight: false,
    license: null,
    note: "Anthropic’s recommended default. Fast mode costs $8 / $40 per 1M tokens.",
    sources: [{ label: "model page", url: "https://platform.claude.com/docs/en/models/opus-5-5/overview" }, { label: "announcement", url: "https://www.anthropic.com/news/claude-opus-5-5" }],
  },
  {
    id: "claude-sonnet-5",
    name: "Claude Sonnet 5",
    provider: "Anthropic",
    apiId: "claude-sonnet-5",
    class: "frontier",
    released: "2026-06-30",
    contextWindow: 1_000_000,
    maxOutput: 128_000,
    price: { input: 2, output: 10, cachedInput: 0.2 },
    openWeight: false,
    license: null,
    note: "New tokenizer: the same text can use up to 1.35× the tokens of Sonnet 4.6.",
    sources: [{ label: "model page", url: "https://platform.claude.com/docs/en/models/sonnet-5/overview" }, { label: "announcement", url: "https://www.anthropic.com/news/claude-sonnet-5" }],
  },
  {
    id: "claude-haiku-4-5",
    name: "Claude Haiku 4.5",
    provider: "Anthropic",
    apiId: "claude-haiku-4-5-20251001",
    class: "fast",
    released: "2025-10-15",
    contextWindow: 200_000,
    maxOutput: 64_000,
    price: { input: 1, output: 5, cachedInput: 0.1 },
    openWeight: false,
    license: null,
    note: "Retirement no sooner than 2026-10-15. Anthropic says Haiku 5.5 is coming.",
    sources: [{ label: "model page", url: "https://platform.claude.com/docs/en/models/haiku-4-5/overview" }, { label: "announcement", url: "https://www.anthropic.com/news/claude-haiku-4-5" }],
  },
  {
    id: "gpt-6-astra",
    name: "GPT-6 Astra",
    provider: "OpenAI",
    apiId: "gpt-6-astra",
    class: "frontier",
    released: "2026-09-03",
    contextWindow: 1_050_000,
    maxOutput: 128_000,
    price: { input: 10, output: 50, cachedInput: 1 },
    openWeight: false,
    license: null,
    note: "Prompts over 272K input tokens cost 2× input and 1.5× output for the whole request.",
    sources: [{ label: "model page", url: "https://developers.openai.com/api/docs/models/gpt-6-astra" }, { label: "pricing", url: "https://developers.openai.com/api/docs/pricing" }, { label: "announcement", url: "https://openai.com/index/gpt-6-astra/" }],
  },
  {
    id: "gpt-6-sol",
    name: "GPT-6 Sol",
    provider: "OpenAI",
    apiId: "gpt-6-sol",
    class: "frontier",
    released: "2026-09-22",
    contextWindow: 1_050_000,
    maxOutput: 128_000,
    price: { input: 2, output: 10, cachedInput: 0.2 },
    openWeight: false,
    license: null,
    note: "The model OpenAI’s Codex docs now point to. Prompts over 272K input tokens cost 2× input and 1.5× output.",
    sources: [{ label: "model page", url: "https://developers.openai.com/api/docs/models/gpt-6-sol" }, { label: "pricing", url: "https://developers.openai.com/api/docs/pricing" }, { label: "announcement", url: "https://openai.com/index/introducing-gpt-6-sol-and-luna/" }],
  },
  {
    id: "gpt-6-luna",
    name: "GPT-6 Luna",
    provider: "OpenAI",
    apiId: "gpt-6-luna",
    class: "fast",
    released: "2026-09-22",
    contextWindow: 1_050_000,
    maxOutput: 128_000,
    price: { input: 0.1, output: 0.5 },
    openWeight: false,
    license: null,
    note: "OpenAI’s cheapest current tier. Prompts over 272K input tokens cost 2× input and 1.5× output.",
    sources: [{ label: "model page", url: "https://developers.openai.com/api/docs/models/gpt-6-luna" }, { label: "pricing", url: "https://developers.openai.com/api/docs/pricing" }, { label: "announcement", url: "https://openai.com/index/introducing-gpt-6-sol-and-luna/" }],
  },
  {
    id: "grok-4-7",
    name: "Grok 4.7",
    provider: "xAI",
    apiId: "grok-4.7",
    class: "frontier",
    released: "2026-09-21",
    contextWindow: 500_000,
    maxOutput: null,
    price: { input: 2, output: 6, cachedInput: 0.5 },
    openWeight: false,
    license: null,
    note: "Prompts of 200K+ tokens cost $4 / $12. xAI publishes no output-token limit.",
    sources: [{ label: "model page", url: "https://docs.x.ai/developers/models/grok-4.7.md" }, { label: "pricing", url: "https://docs.x.ai/developers/models.md" }, { label: "announcement", url: "https://x.ai/news/grok-4-7" }],
  },
  {
    id: "grok-build-0-1",
    name: "Grok Build 0.1",
    provider: "xAI",
    apiId: "grok-build-0.1",
    class: "fast",
    released: "2026-05-29",
    contextWindow: 256_000,
    maxOutput: null,
    price: { input: 1, output: 2 },
    openWeight: false,
    license: null,
    note: "xAI’s coding model, in public beta. Prompts of 200K+ tokens cost $2 / $4. No published benchmarks.",
    sources: [{ label: "model page", url: "https://docs.x.ai/developers/models/grok-build-0.1.md" }, { label: "announcement", url: "https://x.ai/news/grok-build-0-1" }],
  },
  {
    id: "gemini-3-1-pro",
    name: "Gemini 3.1 Pro",
    provider: "Google",
    apiId: "gemini-3.1-pro-preview",
    class: "frontier",
    released: "2026-02-19",
    contextWindow: 1_048_576,
    maxOutput: 65_536,
    price: { input: 2, output: 12 },
    openWeight: false,
    license: null,
    note: "Still in preview. Prompts over 200K tokens cost $4 / $18.",
    sources: [{ label: "model page", url: "https://ai.google.dev/gemini-api/docs/models/gemini-3.1-pro-preview" }, { label: "pricing", url: "https://ai.google.dev/gemini-api/docs/pricing" }, { label: "model card", url: "https://deepmind.google/models/model-cards/gemini-3-1-pro/" }],
  },
  {
    id: "gemini-3-8-flash",
    name: "Gemini 3.8 Flash",
    provider: "Google",
    apiId: "gemini-3.8-flash",
    class: "fast",
    released: "2026-09-02",
    contextWindow: 1_048_576,
    maxOutput: 65_536,
    price: { input: 0.75, output: 3.75 },
    openWeight: false,
    license: null,
    note: "Introductory price through 2026-12-31, rising to $1.50 / $7.50 on 2027-01-01.",
    sources: [{ label: "model page", url: "https://ai.google.dev/gemini-api/docs/models/gemini-3.8-flash" }, { label: "pricing", url: "https://ai.google.dev/gemini-api/docs/pricing" }, { label: "model card", url: "https://deepmind.google/models/model-cards/gemini-3-8-flash/" }],
  },
  {
    id: "qwen3-8-max",
    name: "Qwen3.8-Max",
    provider: "Alibaba Qwen",
    apiId: "qwen3.8-max",
    class: "open-weight",
    released: "2026-08-12",
    contextWindow: 262_144,
    maxOutput: 131_072,
    price: { input: 2, output: 6 },
    openWeight: true,
    license: "Qwen3.8-Max License (MIT-style, revenue limits)",
    note: "Open weights are Qwen3.8-2.4T-A95B, text-only with 262K native context. The hosted API adds vision and 1M context.",
    sources: [{ label: "model card", url: "https://huggingface.co/Qwen/Qwen3.8-2.4T-A95B" }, { label: "api pricing", url: "https://www.qwencloud.com/models/qwen3.8-max" }],
  },
  {
    id: "qwen3-8-27b",
    name: "Qwen3.8-27B",
    provider: "Alibaba Qwen",
    apiId: "qwen3.8-27b",
    class: "open-weight",
    released: "2026-08-14",
    contextWindow: 262_144,
    maxOutput: 131_072,
    price: { input: 0.5, output: 3 },
    openWeight: true,
    license: "Apache-2.0",
    note: "Dense 27B model: the most practical current option to run on your own GPU.",
    sources: [{ label: "model card", url: "https://huggingface.co/Qwen/Qwen3.8-27B" }, { label: "api pricing", url: "https://www.qwencloud.com/models/qwen3.8-27b" }],
  },
  {
    id: "deepseek-v4-pro",
    name: "DeepSeek-V4-Pro",
    provider: "DeepSeek",
    apiId: "deepseek-v4-pro",
    class: "open-weight",
    released: "2026-08-13",
    contextWindow: 1_048_576,
    maxOutput: 393_216,
    price: { input: 1.32, output: 3.96 },
    openWeight: true,
    license: "MIT",
    note: "Peak-hour API price. Off-peak is half: $0.66 / $1.98. 1.6T total, 49B active parameters.",
    sources: [{ label: "model card", url: "https://huggingface.co/deepseek-ai/DeepSeek-V4-Pro-0813" }, { label: "api pricing", url: "https://api-docs.deepseek.com/quick_start/pricing" }],
  },
  {
    id: "deepseek-v4-1-flash",
    name: "DeepSeek-V4.1-Flash",
    provider: "DeepSeek",
    apiId: "deepseek-flash",
    class: "open-weight",
    released: "2026-09-10",
    contextWindow: 1_048_576,
    maxOutput: 393_216,
    price: { input: 0.3, output: 1.2 },
    openWeight: true,
    license: "MIT",
    note: "Peak-hour API price. Off-peak is half: $0.15 / $0.60.",
    sources: [{ label: "model card", url: "https://huggingface.co/deepseek-ai/DeepSeek-V4.1-Flash" }, { label: "api pricing", url: "https://api-docs.deepseek.com/quick_start/pricing" }],
  },
  {
    id: "kimi-k3",
    name: "Kimi K3",
    provider: "Moonshot AI",
    apiId: "kimi-k3",
    class: "open-weight",
    released: "2026-07-27",
    contextWindow: 1_048_576,
    maxOutput: 1_048_576,
    price: { input: 3, output: 15, cachedInput: 0.3 },
    openWeight: true,
    license: "Kimi K3 License (MIT-style, revenue limits)",
    note: "2.8T total, 104B active parameters. Release date is when the weights went public.",
    sources: [{ label: "model card", url: "https://huggingface.co/moonshotai/Kimi-K3" }, { label: "api quickstart", url: "https://platform.kimi.ai/docs/guide/kimi-k3-quickstart" }, { label: "pricing", url: "https://www.kimi.com/blog/kimi-k3" }],
  },
  {
    id: "glm-5-3",
    name: "GLM-5.3",
    provider: "Z.ai",
    apiId: "glm-5.3",
    class: "open-weight",
    released: "2026-08-14",
    contextWindow: 1_048_576,
    maxOutput: 131_072,
    price: { input: 1.4, output: 4.4, cachedInput: 0.26 },
    openWeight: true,
    license: "GLM-5.3 License (MIT-style)",
    note: "744B total, 40B active parameters, reasoning always on.",
    sources: [{ label: "model card", url: "https://huggingface.co/zai-org/GLM-5.3" }, { label: "api docs", url: "https://docs.z.ai/guides/llm/glm-5.3" }, { label: "pricing", url: "https://docs.z.ai/guides/overview/pricing" }],
  },
  {
    id: "minimax-m3",
    name: "MiniMax-M3",
    provider: "MiniMax",
    apiId: "MiniMax-M3",
    class: "open-weight",
    released: "2026-06-01",
    contextWindow: 1_048_576,
    maxOutput: null,
    price: { input: 0.3, output: 1.2 },
    openWeight: true,
    license: "MiniMax Community License (attribution required)",
    note: "Price after a permanent 50% discount, for prompts up to 512K tokens; $0.60 / $2.40 above that.",
    sources: [{ label: "model card", url: "https://huggingface.co/MiniMaxAI/MiniMax-M3" }, { label: "pricing", url: "https://platform.minimax.io/docs/guides/pricing-paygo" }],
  },
  {
    id: "mistral-medium-3-5",
    name: "Mistral Medium 3.5",
    provider: "Mistral AI",
    apiId: "mistral-medium-3-5",
    class: "open-weight",
    released: "2026-05-22",
    contextWindow: 262_144,
    maxOutput: null,
    price: { input: 1.5, output: 7.5 },
    openWeight: true,
    license: "Modified MIT (no rights above $20M monthly revenue)",
    note: "Replaces Devstral 2, which Mistral retired from its API on 2026-07-31.",
    sources: [{ label: "model card", url: "https://huggingface.co/mistralai/Mistral-Medium-3.5-128B" }, { label: "api docs", url: "https://docs.mistral.ai/models/mistral-medium-3-5-26-04" }],
  },
  {
    id: "gpt-oss-120b",
    name: "gpt-oss-120b",
    provider: "OpenAI",
    apiId: "gpt-oss-120b",
    class: "open-weight",
    released: "2025-08-05",
    contextWindow: 131_072,
    maxOutput: 131_072,
    price: null,
    openWeight: true,
    license: "Apache-2.0",
    note: "117B total, 5.1B active parameters. Runs on a single 80GB GPU. No OpenAI API list price.",
    sources: [{ label: "model page", url: "https://developers.openai.com/api/docs/models/gpt-oss-120b" }, { label: "announcement", url: "https://openai.com/index/introducing-gpt-oss/" }],
  },
  {
    id: "gpt-oss-20b",
    name: "gpt-oss-20b",
    provider: "OpenAI",
    apiId: "gpt-oss-20b",
    class: "open-weight",
    released: "2025-08-05",
    contextWindow: 131_072,
    maxOutput: 131_072,
    price: null,
    openWeight: true,
    license: "Apache-2.0",
    note: "21B total, 3.6B active parameters. Small enough for a laptop with 16GB of memory.",
    sources: [{ label: "model page", url: "https://developers.openai.com/api/docs/models/gpt-oss-20b" }, { label: "announcement", url: "https://openai.com/index/introducing-gpt-oss/" }],
  },
];
